[package]
name = "ced"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path="src/lib.rs"

[[bin]]
name="ced"
path="src/cli/bin.rs"

[features]
cli = []

[dependencies]
regex = "1.5.4"
thiserror = "1.0.25"
