all:
	# All Text
	@cat ./version.txt > ./all.txt
	@cat ./description.txt >> ./all.txt
	@cat ./binary.txt >> ./all.txt
	@cat ./raw/* >> ./all.txt

	# Binary text
	@cat ./version.txt > ./bin.txt
	@cat ./description.txt >> ./bin.txt
	@cat ./binary.txt >> ./bin.txt
